name: Release

on:
  push:
    tags:
      - "v*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Java and Maven
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'

      - name: Publish package
        run: mvn -B package -DskipTests=true -Dgpg.skip=true -Djavadoc.skip=true

      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          omitName: true
          artifacts: 'odps-console-dist-public/target/odpscmd_public.zip'
          token: ${{ secrets.RELEASE_TOKEN }}

      - run: sudo -v ; curl https://gosspublic.alicdn.com/ossutil/install.sh | sudo bash
      - run: ossutil64 -e ${{secrets.OSS_ENDPOINT}} -i ${{secrets.OSS_KEY_ID}} -k ${{secrets.OSS_KEY_SECRET}} cp odps-console-dist-public/target/odpscmd_public.zip oss://maxcompute-repo/odpscmd/latest/ -f
